# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Label to use when marking an issue as stale
staleLabel: stale

pulls:
  # Give more time before closing PRs
  daysUntilClose: 21
  # Comment to post when marking a PR as stale. Set to `false` to disable
  markComment: >
    This PR has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
  # Comment to post when closing a stale PR. Set to `false` to disable
  closeComment: >
    This PR has been automatically closed due to inactivity. Please reopen
    this PR or a new one if you plan to follow-up on it. Thank you for your
    contributions.
